name: CI Pipeline for Project 1

on:
  push:
    branches: [main]
    paths:
      - 'Project1/**'
  pull_request:
    branches: [main]
    paths:
      - 'Project1/**'

jobs:
  code_quality:
    name: Code Quality Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@master
        with:
          output: results.sarif
          format: sarif
          gh-code-scanning-compat: true
          max-allowed-issues: 2147483647

  test_selection:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: code_quality
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run Unit Tests
        run: pytest

  notify:
    name: Send Slack Notification
    runs-on: ubuntu-latest
    needs: [code_quality, test_selection]
    steps:
      - name: Notify Slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL }}"
          slack-message: "✅ CI pipeline duly completed and i'm very super happy!"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
